name: test

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: Check out this repo
      uses: actions/checkout@v2
    - name: Fetch latest data
      run: |-
        current_date=$(date +"%Y-%m-%d %H:%M:%S")
        echo $current_date >> test.txt
    - name: Commit and push if it changed
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |-
        git config --global user.name "Automated"
        git config --global user.email "ciepielajan@gmail.com"
        git add test.txt
        timestamp=$(date -u +"%Y-%m-%d %H:%M:%S")
        git commit -m "Latest data: ${timestamp}" || exit 0
        git push
